import { useQuery } from "@apollo/client";
import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { visitParameterList } from "typescript";
import {
  PostsDocument,
  PostsQuery,
  PostsQueryVariables,
} from "../graphql/generated/generated";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data, error, loading } = useQuery<PostsQuery>(PostsDocument);

  //const { data, error, loading } = useQuery<PostsQuery, PostsQueryVariables>(
  //  PostsDocument
  // this is how you pass visitParameterList...
  // {
  //   variables: {
  //     slug: "abc",
  //   },
  // }
  //);

  if (loading) return <main>Loading</main>;
  if (error) return <main>{error.message}</main>;

  // if we are here, then data has data
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <main className={styles.main}>
          <>
            hello
            {data?.posts?.data[0].attributes?.Title}
          </>
        </main>
      </>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
